### ISSUE TITLE
Tree-shaking support for webpack

### ISSUE THREAD

**Issue by jakubkosinski** [GetStream/react-activity-feed#100]
It looks like the exported library doesn't support tree-shaking so even if you're using only small subset of exported components (e.g. only `<StreamApp>`), the full bundle is loaded, including heavy dependencies like `emoji-mart`, `twitter-text` & `@fortawesome`. Could you export also individual components so that we can import only ones that are actually used?

**Comment by mahboubii** [comment]
@jakubkosinski thanks for reporting this, it should be fixed in [v1.1.0](https://github.com/GetStream/react-activity-feed/releases/tag/v1.1.0).
