### ISSUE TITLE
FlatFeed filtered by reactions

### ISSUE THREAD

**Issue by luisfuertes** [GetStream/react-activity-feed#106]
Im trying to show FlatFeed filtered by reaction, example "like"

How can i get this data with pagination?

I check `doReactionsFilterRequest` but dont have any documentation about it.

I has tried doFeedRequest but pagination didnt work:
```
<FlatFeed
      feedGroup="timeline"
      options={{
        limit: 20,
        kind: 'like',
        user_id: username,
      }}
      doFeedRequest={async (client, feedGroup, userId, options) => {
  
        const res = await client.reactions.filter(options)
        const results = _.get(res, 'results', [])
        const activitiesIds = _.map(results, v => _.get(v, 'activity_id'))
        const activities = await client.getActivities({ ids: activitiesIds })

        return activities
      }}
/>
```

Any idea about how can i list items filtered by reactions in FlatFeed?

**Comment by jaapbakker88** [comment]
@luisfuertes I'm not a 100% sure what you're trying to do here, but there's a couple of things wrong with what you're doing.

First off, you can't filter on a reaction_kind (not sure what you want this to do either). 

Also with the way your doing it pagination doesn't work because onFeedRequest you keep running the same code. So you'll always get the same results.

**Comment by luisfuertes** [comment]
Thanks for answer @jaapbakker88 

I am trying to make a list of only the activities on my timeline that I have liked (like reaction)

This query is working, but of course, as you say, the pagination does not work. I am passing the options that I receive from my FlatFeed to do the query in the doFeedRequest, but these options do not paginate

What would be the correct way to do a timeline only with my "liked" activities?

**Comment by luisfuertes** [comment]
In my opinion FlatFeed should call "doFeedRequest" method every FlatList onEndReached event, with new pagination options.

**Comment by jaapbakker88** [comment]
That's what it does, but as your running the same code on doFeedRequest you're getting the same results. If you want to do it this way, you will have to handle pagination yourself as well.

**Comment by luisfuertes** [comment]
FlatFeed call doFeedRequest every FlatList onEndReached? Are you sure? h

How can i get current list in doFeedRequest function?

**Comment by luisfuertes** [comment]
@jaapbakker88 doFeedRequest is not called when you get to the end of the list.

I can use FlatList onEndReached prop to get it, but i cant set FlatList data and i dont have "client" object out of `doFeedRequest`function.

**Comment by jaapbakker88** [comment]
@luisfuertes Are you actually talking about react native? Just realised we don't have an onEndReached in our react library.

**Comment by luisfuertes** [comment]
Yes, he is the prop to paginate the FlatList (FlatFeed in your component).

**Comment by luisfuertes** [comment]
any update @jaapbakker88 ?

**Comment by jaapbakker88** [comment]
Let's move this to our react-native library as it's not the same codebase. Feel free to open an issue there an mention me in it.
