### ISSUE TITLE
Notification still empty when try comment, like... on the post

### ISSUE THREAD

**Issue by vuonghungvinh** [GetStream/react-activity-feed#11]
I'm using "< NotificationDropdown notify />" to get notification, but when I try comment,like or follow user, but notification still empty

**Comment by Xifeat** [comment]
Same for me actually,

I have my feed, I can like, post on it, but when I click on the notification icon I still have

"no data to display..."

**Comment by JelteF** [comment]
If you want to add a reaction to a feed you have to use [`targetFeeds`](https://getstream.io/docs/js/#reactions_notify-other-feeds). By default this list is empty. To fill it with something you can do it like this:
```jsx
<LikeButton 
    onToggleReaction={
       (kind, activity, data, options) => (
           this.props.onToggleReaction(
                kind, activity, data, {...options, targetFeeds: ["notification:123"]}
           )
       )
    }
/>

**Comment by TamaWhiu** [comment]
> If you want to add a reaction to a feed you have to use [`targetFeeds`](https://getstream.io/docs/js/#reactions_notify-other-feeds). By default this list is empty. To fill it with something you can do it like this:
> 
> ```js-jsx
> <LikeButton 
>     onToggleReaction={
>        (kind, activity, data, options) => (
>            this.props.onToggleReaction(
>                 kind, activity, data, {...options, targetFeeds: ["notification:123"]}
>            )
>        )
>     }
> />
> ```
Hi thanks for the example above.  I'm trying to work out how to achieve a similar thing for adding a comment "CommentField" and  a post "StatusUpdateForm" any guidance will be appreciated.
