### ISSUE TITLE
Add onRequest prop in StatusUpdateForm

### ISSUE THREAD

**Issue by matheusmatos** [GetStream/react-activity-feed#12]
Hi guys,

How about adding the possibility to implement a custom request on `StatusUpdateForm`?

Example of use that I'm thinking: `<StatusUpdateForm onRequest = {activity => {}} />`

It would allow to post an activity on other feed without changing app policies.

Thank you all for the great job.

**Comment by tbarbugli** [comment]
@matheusmatos did you already look at the `to` target feed for this?

**Comment by JelteF** [comment]
This has been fixed. StatusUpdateForm now has a `doRequest` prop.
