### ISSUE TITLE
NotificationDropdown - close dropdown after click activity

### ISSUE THREAD

**Issue by hliangz** [GetStream/react-activity-feed#124]
Hi,

I want to close the dropdown when I click on one of the activities.
Is there a way to do this? eg:

```
handleClickNotification(url) {
   this.props.markAsRead(this.props.activityGroup);

   // to close the notification dropdown
  closeNotificationDropdown();
}

```

Thank you

<img width="479" alt="Screen Shot 2020-11-30 at 7 31 10 pm" src="https://user-images.githubusercontent.com/64247934/100586035-a5f3ab80-3342-11eb-9f82-3393f81fe4aa.png">

**Comment by hliangz** [comment]
> @hliangz how did you achieve this? Looking for the same thing

hi @TylerAHolden  yes, I did
I just tigger the click on it's parent diiv wrapper: `streamContainerRef.current.click();`

**Comment by TylerAHolden** [comment]
I guess that makes sense. It seems like a strange hack... I wish there was an exposed function or something from Stream
