### ISSUE TITLE
Remove requirement of token for initialization 

### ISSUE THREAD

**Issue by TylerAHolden** [GetStream/react-activity-feed#127]
My current understanding is that for a client side token you need to request a user token from a backend (in my case a serverless function) and use that to pass into the StreamApp component. However, the StreamApp component crashes and breaks if it does not receive a proper token: 
```
TypeError: Cannot read property 'data' of undefined
Function.initClientState
src/Context/StreamApp.js:225
  222 | ...state,
  223 | client,
  224 | user: client.currentUser,
> 225 | userData: client.currentUser.data,
      | ^  226 | analyticsClient,
  227 | sharedFeedManagers: {},
  228 | errorHandler: props.errorHandler,
``` 

This is an issue because I do not want to wait on that API call to return a user token in order to initialize streams context which sits at a high level therefore it essentially blocks the entire application.

**Comment by TylerAHolden** [comment]
Any updates on this? This is still an issue...

**Comment by MartinCupela** [comment]
Hi @TylerAHolden , I apologize for the delay in response. Did you manage to find workaround or you are still stuck with crashing StreamApp component? Questions that come into my mind:

1. What would you like to happen, if the StreamApp component didn't require the token? How should other feed components behave?
2. Is it not possible in your scenario to render StreamApp component conditionally - only if the token is available?

Thank you in advance

**Comment by TylerAHolden** [comment]
I can't confirm if this is still an issue since the library has probably been changed quite a bit over the last 9 months.

To answer your questions directly:

1. I would like the StreamApp component to not throw an error for a null/undefined token - it should be acceptable to not have authentication especially for something that requires an API request. The other feed components should return empty states or null/undefined for their components rather than throwing an error.
2. Yes that is part of my workaround, however, my biggest complaint is that when you conditionally render the StreamApp component you MUST ALSO conditionally render every single stream UI component - that is because the stream UI components throw errors if they cannot attach to the StreamApp context.

So my workaround involves conditionally rendering the StreamApp context which wraps a large portion of the application so that is undesirable to conditionally render.. And also conditionally rendering all of the stream components with a 1000ms delay from when the StreamApp component is instantiated to prevent race condition errors.

**Comment by MartinCupela** [comment]
@TylerAHolden I would like to learn more about your architecture, because I want to understand your use case. Would you mind to have a short google meet call in the near future, where we could discuss it?

**Comment by TylerAHolden** [comment]
Sure

**Comment by MartinCupela** [comment]
What is your timezone?

**Comment by TylerAHolden** [comment]
Texas - CST

**Comment by MartinCupela** [comment]
Ok, I am in central Europe so tomorrow I will try to come with more specific day and time possibilities. Is 7am-10am (you local time) window ok for you?

**Comment by juanludlf** [comment]
Hi @TylerAHolden @MartinCupela 

Did you solve this problem?

**Comment by MartinCupela** [comment]
@juanludlf this request is in backlog for now
