### ISSUE TITLE
Ability to display an Empty list component

### ISSUE THREAD

**Issue by sicsol** [GetStream/react-activity-feed#14]
It would be great to have an option to display a custom component if the feeds are empty this is good for all feed types FlatFeed Notification etc.

**Comment by jaapbakker88** [comment]
I've just released version 0.6.8 which includes the `Placeholder` prop on both the `NotificationFeed` and the `FlatFeed` component. It comes with a default, but you can also inject your own component with this prop.  The placeholder displays  only when an initial request has been made, but no data was returned.
