### ISSUE TITLE
Error: You are publicly sharing your App Secret.

### ISSUE THREAD

**Issue by Saleem-digichowk** [GetStream/react-activity-feed#15]
Iʻm getting this error whiling using your service, can you please help. 

Error: You are publicly sharing your App Secret. Do not expose the App Secret in browsers, "native" mobile apps, or other non-trusted environments.

**Comment by JelteF** [comment]
can you show the output of: `npm list getstream` and `npm list react-activity-feed` (or `yarn list` if you use yarn)

**Comment by Saleem-digichowk** [comment]
empapp@0.1.0 D:\event_application
`-- react-activity-feed@0.6.7
  `-- getstream@4.1.0


D:\event_application>npm list react-activity-feed
empapp@0.1.0 D:\event_application
`-- react-activity-feed@0.6.7

**Comment by JelteF** [comment]
Okay, in that case I think you are putting the secret from the dashboard in the token prop, not a user token. To generate a user token follow the docs here:
https://getstream.io/docs/js/#setup

If this is not the case please send a support email with how you initialize the client.

**Comment by JelteF** [comment]
Since you haven't responded I assume this was indeed the case. I will close this issue.
