### ISSUE TITLE
CSS Module parse failed

### ISSUE THREAD

**Issue by dco5** [GetStream/react-activity-feed#19]
Hello, 
I am getting this error when trying to use react-activity-feed

`ERROR in ./node_modules/emoji-mart/css/emoji-mart.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .emoji-mart,
| .emoji-mart * {
|   box-sizing: border-box;
 @ ./node_modules/react-activity-feed/dist/index.es.js 27:0-39
 @ ./src/js/containers/notifications/notifications.js
 @ ./src/js/containers/nav.js
 @ ./src/js/index.js
 @ multi babel-polyfill ./src/js/index.js

ERROR in ./node_modules/@webscopeio/react-textarea-autocomplete/style.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .rta {
|   position: relative;
|   font-size: 18px;
 @ ./node_modules/react-activity-feed/dist/index.es.js 26:0-59
 @ ./src/js/containers/notifications/notifications.js
 @ ./src/js/containers/nav.js
 @ ./src/js/index.js
 @ multi babel-polyfill ./src/js/index.js

ERROR in ./node_modules/react-activity-feed/dist/index.es.css 2:6
Module parse failed: Unexpected token (2:6)
You may need an appropriate loader to handle this file type.
| body,
> [class^='raf-'],
| [class*=' raf-'] {
|   font-family: Avenir, Arial, Helvetica, sans-serif;
 @ ./src/js/containers/notifications/notifications.js 15:0-48
 @ ./src/js/containers/nav.js
 @ ./src/js/index.js
 @ multi babel-polyfill ./src/js/index.js`

I already have the css loader configured in webpack
      {
        test: /\.(css|scss)$/,
        exclude: /node_modules/,
        loaders: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader?indentedSyntax=false'],
      },

Thanks!

**Comment by JelteF** [comment]
I guess you shouldn't exclude `/node_modules/` in you loader. So like this:
```
{
test: /.(css|scss)$/,
loaders: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader?indentedSyntax=false'],
},
```

**Comment by dco5** [comment]
That worked! Thank you!
