### ISSUE TITLE
NotificationDropDown component not return notification in group. like first return connection_request verb after that it's return meeting_scedule_reuest after that again it's return connection_request.

### ISSUE THREAD

**Issue by parthsavaliya1** [GetStream/react-activity-feed#202]
[
![Screenshot (311)](https://user-images.githubusercontent.com/49479934/112327626-962a1980-8cdb-11eb-879e-a70cc75b64e8.png)
](url)

**Comment by arnautov-anton** [comment]
Hi, @parthsavaliya1, could you please share a bit more information about this issue? Like how do we replicate it, what is desired behaviour and what's currently bothering you. Screnshots/code snippets/videos, anything that we could work with, thanks!
