### ISSUE TITLE
NotificationDropdown

### ISSUE THREAD

**Issue by dco5** [GetStream/react-activity-feed#22]
Is there a way to change the notification IconBadge in the NotificationDropdown? Or I will have to create my own NotificationDropdown?

**Comment by jaapbakker88** [comment]
Hey! Right now this is not possible, but you can do this yourself quite easily as it's just a small wrapper component with some dropdown logic. It's composed out of the following three components you have access to:

- `<IconBadge />` which you can customize the icon of
- `<DropDownPanel />`
- `<NotificationFeed />`

Let me know if you need any help!
