### ISSUE TITLE
Is there a smaller source of basic components?

### ISSUE THREAD

**Issue by andrewbihl** [GetStream/react-activity-feed#222]
Hi there,

I am trying out GetStream for the first time. Is there a smaller source of basic components to use with React? The size of this package makes it a non-starter for almost any real-world product I am sure, but I haven't found guidance on what people are doing instead. Just pull the pieces of the source code that you need? Is there any easier solution?

**Comment by mahboubii** [comment]
Hey @andrewbihl, we recently released the [v1](https://github.com/GetStream/react-activity-feed/releases/tag/v1.0.0) version of the library which drastically reduces the bundle size. You can also import single components if you want to skip the bigger ones.
