### ISSUE TITLE
Is it not compatible with newer versions of React?

### ISSUE THREAD

**Issue by rblalock** [GetStream/react-activity-feed#223]
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: audio@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.x" from react-activity-feed@0.10.9
```

**Comment by mahboubii** [comment]
Hey @rblalock, the current version should support React v17. If you are getting an error you might need to tweak your npm install command. 
We are about to release a new version of the library with official support for v17 and typescript out of the box in few weeks.

**Comment by rblalock** [comment]
Yeh I'm getting the error posted above.  I've tried with --force and the one that allows legacy deps but it won't build on a brand new NextJS app.

**Comment by rblalock** [comment]
For example... using --legacy-peer-deps (which is the only way npm install will work with a new NextJS project), I get this later on:

```
Can't resolve 'babel-runtime/core-js/object/values'
```

**Comment by mahboubii** [comment]
@rblalock should be fixed in [v1](https://github.com/GetStream/react-activity-feed/releases/tag/v1.0.0).
