### ISSUE TITLE
Cannot import from react-activity-feed 1.0

### ISSUE THREAD

**Issue by yumoraby** [GetStream/react-activity-feed#260]
Getting the following error when compiling app in Docker, running locally in a dev environment is fine no issues. 

```bash
Module '"react-activity-feed"' has no exported member 'useFeedContext'
```

**Comment by mahboubii** [comment]
@yumoraby could you share more info on how to reproduce this issue?

**Comment by mahboubii** [comment]
This looks like a setup issue, can you try with the [example app](https://github.com/GetStream/react-activity-feed/tree/main/example) we have and see if you can break it on linux?

**Comment by yumoraby** [comment]
> This looks like a setup issue, can you try with the [example app](https://github.com/GetStream/react-activity-feed/tree/main/example) we have and see if you can break it on linux?

Built the example app and it works. For the example i ran:

yarn install on the parent directory, and yarn install on the example directory.

However still getting the same problem when running 'yarn run build':

```bash
Module '"react-activity-feed"' has no exported member 'useStreamContext'.  TS2305
#25 144.3
#25 144.3       1 | import React, { Fragment, useCallback, useEffect } from 'react';
#25 144.3     > 2 | import { FlatFeed, Activity, InfiniteScrollPaginator, Dropdown, Link, FlatFeedProps, useStreamContext } from 'react-activity-feed';
#25 144.3         |                                                                                      ^
#25 144.3       3 | import { useDispatch } from 'react-redux';
#25 144.3       4 | import { push } from 'connected-react-router';
#25 144.3       5 | import { QueryProfileUsername } from '../../typings';
#25 144.3
#25 144.3
#25 144.4   error Command failed with exit code 1.
#25 144.4   info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Will try recall the e

**Comment by yumoraby** [comment]
I tried a number of steps and found that it worked without issue on Windows and macos. In the end i could not find a solid fix, so added 
// @ts-ignore to the import lines, and was able to build the react app in Docker and on Linux.

Have no idea why some of the functions do not export, whilst other imports work without issue. 

Closing this issue

**Comment by ellioseven** [comment]
I'm running into exactly the same issue. I think this should be re-opened because simply ignoring it will loose TypeScript benefits.

**Comment by ellioseven** [comment]
Something very strange here, I can see that the `src` and `dist` directories don't match up:

![image](https://user-images.githubusercontent.com/4191120/117914950-9c299780-b327-11eb-8b36-89750e7965f8.png)

Note `src/context` and `dist/Context`.

If I rename `dist/Context` to `dist/context`, then it works, however I get a bunch of warnings:

```
node_1      | There are multiple modules with names that only differ in casing.
node_1      | This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
node_1      | Use equal casing. Compare these module identifiers:
node_1      | * /srv/node_modules/rc-picker/node_modules/moment/locale/en-SG.js
node_1      |     Used by 2 module(s), i. e.
node_1      |     /srv/node_modules/rc-picker/node_modules/moment/locale sync /^\.\/.*$/
node_1      | * /srv/node_modules/rc-picker/node_modules/moment/locale/en-sg.js
node_1      |     Used by 2 module(s), i. e.
node_1      |     /srv/node_modules/rc-picker/node_modules/moment/locale sync /^\.\/.*$/
```

**Comment by ellioseven** [comment]
I managed to solve the moment.js warnings by pinning the moment.js version in `package.json`:

```
"resolutions": {
  "moment": "^2.29.1"
}
```

However, I'm still seeing the context difference in `src` and `dist`. @yumoraby Perhaps other OS's aren't case sensitive, so users only Linux will see this when consuming anything in context?

@mahboubii I can see `context` was previously named `Context` in previous commits. Maybe the package needs to be rebuilt then pushed to npm?

**Comment by mahboubii** [comment]
@ellioseven @yumoraby Thanks for reporting this issue, please bump to `v1.0.1`.
