### ISSUE TITLE
StatusUpdateForm pasting non-plaintext creates an error

### ISSUE THREAD

**Issue by geshuming** [GetStream/react-activity-feed#278]
Simply copy pasting the "New Post" element in the same component will result in an error. Pasting other non-plaintext formats will also create an error

![statusupdateform-error](https://user-images.githubusercontent.com/43642522/123568152-500eb580-d7f6-11eb-95f8-760e0cca250d.gif)

**Comment by arnautov-anton** [comment]
Hey, @geshuming, thank you for submitting this issue! I'll take a look ASAP and get back to you.

**Comment by arnautov-anton** [comment]
Issue has been fixed, merged and the new version of the SDK released. Please update your package and let me know if something else pops up! :)
