### ISSUE TITLE
font-family in index.css is applied to the body also

### ISSUE THREAD

**Issue by gcwokeup** [GetStream/react-activity-feed#28]
https://github.com/GetStream/react-activity-feed/blob/master/src/App.css#L1
It is currently applying the the style to `body` as well. I believe you meant for it to be applied only on its children.

I think it should be:
`
body [class^='raf-'],
body [class*=' raf-'] {
  font-family: Avenir, Arial, Helvetica, sans-serif;
  box-sizing: border-box;
}
`

Created a pull request for it:
https://github.com/GetStream/react-activity-feed/pull/29

**Comment by JelteF** [comment]
This is fixed as of v0.7.4
