### ISSUE TITLE
LikeButton rerenders all activities in the feed when it shouldn't

### ISSUE THREAD

**Issue by geshuming** [GetStream/react-activity-feed#280]
```
<StreamApp apiKey={apiKey} appId={appId} token={activityFeedToken}>
        <FlatFeed
          feedGroup={feedGroup}
          userId={feedId}
          notify
          Activity={(props) => 
            <Activity
              {...props}
              Footer={() => (
                <div style={{ padding: "8px 16px" }}>
                  <LikeButton {...props} />
                  <ActivityFeedComments activity={props.activity} user={user} />
                </div>
              )}
            />
          }
        />
      </StreamApp>
```

When I press a like on one activity, it would rerender all the activities in the FlatFeed. I feel like it should only rerender the LikeButton component, it shouldn't even rerender my custom ActivityFeedComments component, or the other Activity components.

Or am I doing something wrong?

**Comment by geshuming** [comment]
I figured out that it's because the LikeButton is wrapped inside a functional component, and so that anonymous component is actually the component getting rerendered:
```
Footer={() => (
  <div style={{ padding: "8px 16px" }}>
    <LikeButton {...props} />
    <ActivityFeedComments activity={props.activity} user={user} />
  </div>
)}
```
should change to
```
Footer={
  <div style={{ padding: "8px 16px" }}>
    <LikeButton {...props} />
    <ActivityFeedComments activity={props.activity} user={user} />
  </div>
}
```

I was following the tutorial on https://getstream.io/react-activity-feed/tutorial/#comments, so maybe the code snippet there should be updated?

**Comment by arnautov-anton** [comment]
Thank you for letting us know about this issue, @geshuming! Footer property allows you to use function component for you to be able to access the render properties of the Footer. You'd usually define such component somewhere in your codebase and thus it wouldn't be anonymous anymore and wouldn't cause unwanted renders which is [default behaviour of the React](https://reactjs.org/docs/faq-functions.html#arrow-function-in-render).

You're right with the tutorial though, this can and will cause confusion so we'll definitely look into it. :)
