### ISSUE TITLE
Activity not refreshing after adding reaction

### ISSUE THREAD

**Issue by Rykuno** [GetStream/react-activity-feed#284]
When utilizing the built in `<CommentField activity={activity} />` component, whenever a comment is created, it seems to automatically update the activity to reflect said submitted comment. 

Although when making the `reactions.add()` call on the backend, it does not trigger a live update to the activity within the flat feed. I'm rather new to the library and might be missing something. I'm utilizing a ported editor so I'm unable to extend the `CommentField` component as necessary. 

After refreshing the page, the reactions from utilizing the `CommentField` and my Custom editor appear identical in structure and data so I'm a bit lost here.

```js
  const reaction = await client.reactions.add(
      "comment",
      data.activityId,
      { text },
      { userId: user.id },
    )
 ```

**Comment by benhunterandrewrobertson** [comment]
Hi @Rykuno, how did you end up resolving this? Thanks
