### ISSUE TITLE
Error: Cannot read property 'cancel' of undefined - NextJS

### ISSUE THREAD

**Issue by Rykuno** [GetStream/react-activity-feed#285]
When navigating between Pages within NextJS, the streams upon subsequent pages appear failing to close. I might be wrong about the implication but it seems relatively serious. 

I'm using a dummy project created in my dashboard for this example. 

### Error
```
TypeError: Cannot read property 'cancel' of undefined
    at FeedManager.eval (FeedManager.js?3b0e:917)
    at step (tslib.es6.js?9ab4:102)
    at Object.eval [as next] (tslib.es6.js?9ab4:83)
    at fulfilled (tslib.es6.js?9ab4:73)
  ```
  
I found an issue with related somewhat to this but it was closed due to a contributor unable to reproduce it. So I've provided an example repo(Since codesandbox does not like NextJS routing too well) with the environment in which the error occurs.  

### Repo to reproduce the error
https://github.com/Rykuno/getstream-error-example

### Instructions 
`git clone`, `yarn install` and navigate between the users on the NavBar with the console open to view the error.

**Comment by arnautov-anton** [comment]
Hey, @Rykuno! Thank you for taking your time and sharing the reproducible code with us. The PR that addresses this is on the way and should be out in no time. I'll close this issue once it gets merged and release is ready. :)
