### ISSUE TITLE
FlatFeed notifier text not working , when we change local language of feed activity

### ISSUE THREAD

**Issue by AnkurSavaliya** [GetStream/react-activity-feed#288]
I give i18instance with language Hindi in Stream APP and  when we get new feed activity it show Notifier text in english, but i want this Notifier text also in Hindi.

Notifier text in FlateFeed : 
"You have 1 new activity"

my expected out put is :  "आपके पास 1 नई गतिविधि है"

**Comment by arnautov-anton** [comment]
Hey, @AnkurSavaliya! This is not an issue but rather default behaviour of the `FlatFeed` which uses its own `DefaultNotifier` with custom properties `labelPlural` and `labelSingle` which do not get translated. 

You could override this default notifier by importing `NewActivitiesNotification` and passing it down to `FlatFeed`'s `Notifier` property as such :
```ts
import { NewActivitiesNotification } from 'react-activity-feed';

<FlatFeed Notifier={NewActivitiesNotification} {...rest} />
```
But this defaults to these translations which might not suit you:
```json
"You have 1 new notification": "आपके पास 1 नई नोटिफिकेशन है",
"You have {{ notificationCount }} new notifications": "आपके पास {{ notificationCount }} नई नोटिफिकेशन्स है",
```
In that case you could also create your own label function by taking look at our [source](https://github.com/GetStream/react-activity-feed/blob/fa2ca8be17005f85a78fed57e1e0a03b5ca66f41/src/components/NewActivitiesNotification.tsx#L47) and then passing such function down to `NewActivitiesNotification` components `labelFunction` property which would then render the return value of this function.

Let me know if you have any other questions and I'll try to answer them as soon as possible.

**Comment by AnkurSavaliya** [comment]
I will check and updated you soon.
Thank you!
