### ISSUE TITLE
Mark notification as read

### ISSUE THREAD

**Issue by dco5** [GetStream/react-activity-feed#30]
Hello, is there a way to mark an ActivityGroup as read once you click on the Notification? I am building notifications for my own type of Groups but I can't figure out how to mark them as read when the onClickNotification is triggered. I was examining your Notification.js but I see that the onClickNotification comes from the props, so I followed the trail up, but could not figure out where onClickNotification si coming from.

Thanks!

**Comment by JelteF** [comment]
Since version 0.7.0 you can mark activity groups as seen/read easily using the onMarkAsRead/onMarkAsSeen callbacks supplied in the the props to the `Group` component
Something like the following should work (untested code follows):

```jsx
<NotificationFeed Group={(props) => {
    return <Notification {...props} onClickNotification={(group) => {props.onMarkAsRead(group)}} />
}}/>

**Comment by dco5** [comment]
Yes it works! But the activity group stills shows, I though if the activity group was read it would not be shown anymore, how would I remove? I tried onRemoveActivity but it did not worked.

**Comment by dco5** [comment]
So I am using this, and it works, but not sure if this is the best way to do it:

```
  handleClickNotification(url) {
    const activities = this.props.activityGroup.activities;
    activities.map(activity => {this.props.removeActivity(activity.id);});
    this.props.closeMessageNotification();
    this.props.markAsRead(this.props.activityGroup);
    this.props.history.push(url);
  }
```

**Comment by JelteF** [comment]
Yeah that should work. Another way that would work is something like this:

```
<NotificationFeed Group={(props) => {
    return props.activityGroup.read ? 
         null :
         <Notification {...props} onClickNotification={(group) => {props.onMarkAsRead(group)}} />
}}/>
```

That way it simply doesn't render read groups.

**Comment by dco5** [comment]
Thanks so much for your help!

**Comment by eddievlagea** [comment]
Does this work for React Native as well?

**Comment by humbkr** [comment]
I just wasted 2 hours on this, to make it work with a custom Notification component, in your component you have to use the useFeedContext hook:
```
function Notification({ activityGroup }: NotificationProps) {
  const feed = useFeedContext()

  const onClick = async () => {
    await feed.onMarkAsRead(activityGroup)
  }
  
  return (
    <div onClick={onClick}>
       ...
    </div>
  )
}
```
