### ISSUE TITLE
Typescript Types hard to extend properly

### ISSUE THREAD

**Issue by valoricDe** [GetStream/react-activity-feed#348]
Hey there.
After building my app I would like to strengthen the types I'm using to get away from 'any's.

My types are looking like:

```
export interface IFeedUserType {
  name?: string
  displayName?: string
  profileImage: UrlString
  followerCount: number
}
```
I want to give it to `EnrichedUser<IFeedUserType>` but EnrichedUser is expecting to extend a generic record which has no fixed property key set. `export type UR = Record<string, unknown>;`

<img width="584" alt="Bildschirmfoto 2022-04-07 um 11 53 18" src="https://user-images.githubusercontent.com/22564188/162172968-16d01554-6056-4bb5-988d-33a35a61d8de.png">

I tried to used `EnrichedUser<Partial<IFeedUserType>>` but then I loose all autocompletion in Intellij

**To Reproduce**

Import react-acitivty-feed 
create fixed type and feed into Enriched*

**Expected behavior**

I would expect to clarify the data structure buy creating types

**Additional context**

"react-activity-feed": "1.4.0",

Any help is highly welcome :)

**Comment by MartinCupela** [comment]
Hey @valoricDe, thank you for the question. Try to change the `interface IFeeduserType` to `type IFeedUserType`.

This discussion may be related to your question:

https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024

Did this answer help you?

**Comment by valoricDe** [comment]
Interesting. Yes, switching to types helped. Thank you for the pointer 👍
