### ISSUE TITLE
FlatFeed: filter activity by Target

### ISSUE THREAD

**Issue by TamaWhiu** [GetStream/react-activity-feed#4]
Related to [#3](https://github.com/GetStream/react-activity-feed/issues/3), I'm looking for a way to filter a FlatFeed by Target eg. Only show activities for a particular Group ID stored in Target.  

Currently stepping thru the FlatFeed.js focusing on "FeedRequestOptions" - please suggest the best approach to achieve this.

**Comment by TamaWhiu** [comment]
If you have a similar use case, get in-touch with support, they're very helpful and addressed it quickly.

**Comment by matheusmatos** [comment]
Guys, I have a similar use case, but I'm thinking of another solution. Changing policies would allow a malicious user to post to an unauthorized feed. Instead, would be great if I could implement a custom request to my server. Maybe something as `onRequest` prop. What do you guys think?

**Comment by tbarbugli** [comment]
@matheusmatos can you create a new issue for this?
