### ISSUE TITLE
FollowButton missing from package

### ISSUE THREAD

**Issue by dschoon** [GetStream/react-activity-feed#45]
When trying to import the FollowButton, I receive an error saying it doesn't exist...

`Attempted import error: 'FollowButton' is not exported from 'react-activity-feed'`

Is it just not implemented yet?

https://getstream.github.io/react-activity-feed/#followbutton

**Comment by tbarbugli** [comment]
AFAIK it's implemented but not exported

**Comment by JelteF** [comment]
@jaapbakker88 can you also change the callback prop name to `onClick` instead of `clicked` if that's the case. Since it's not exported yet that's not a breaking change now.

**Comment by jaapbakker88** [comment]
@dschoon I updated the library to version `0.9.9` which exports the FollowButton. Mind that the `clicked` prop changed to `onClick` (cc @JelteF)
