### ISSUE TITLE
Public Feeds

### ISSUE THREAD

**Issue by liran-co** [GetStream/react-activity-feed#47]
I'm confused on how to display public feeds. Using this library requires a user token to be generated, so how would I go about creating a publicly viewable feed?

**Comment by JelteF** [comment]
For public feeds stream has to change some settings for your app in our admin panel. Please contact us with details on which feed(s)/feedgroup(s) for which of your apps, should be public and if they should be readable+writable by anyone or only readable.

**Comment by vonbv** [comment]
Is this still a manual thing? Meaning that you have to configure something in the back-end? Is a public feed still not possible via code?

**Comment by ferhatelmas** [comment]
@vonbv yes, that's case. It's an API but internal. We will expose it and all feed management though.

**Comment by vonbv** [comment]
@ferhatelmas thanks for confirming it. Is there an ETA on when it will be exposed?
