### ISSUE TITLE
IconBadge Customizable within NotificationDropDown

### ISSUE THREAD

**Issue by sheng-duetto** [GetStream/react-activity-feed#50]
One of examples listed under https://getstream.github.io/react-activity-feed/#iconbadge shows that we can customize the icon with our own by passing it children props.

We were hoping to leverage this customize icon feature on the `IconBadge` that gets rendered as part of the `NotificationDropDown` component. 

Is it feasible to have `NotificationDropDown` accept an optional Renderable prop that can be passed as a child prop to its inner reference to `IconBadge` ?

**Comment by jaapbakker88** [comment]
@sheng-duetto I just updated 'react-activity-feed' to '0.9.15'. I added an `Icon` prop to the NotificationDropdown to make the icon customizable. You can see in in action here: https://getstream.github.io/react-activity-feed/#!/NotificationDropdown/2

Feel free to reach out if there's anything else we can help you with.

**Comment by sheng-duetto** [comment]
Sorry for the delayed response I've been away. Thank you again for your help!
