### ISSUE TITLE
Provide onMarkAsRead functionality to NotificationDropDown Header

### ISSUE THREAD

**Issue by sheng-duetto** [GetStream/react-activity-feed#52]
Hi react-activity-feed team,

One of the feature we're trying to build on top of the `NotificationDropDown` is the ability to click on a link in the header of the dropdown that functions as "Mark All Notifications as Read".

For individual notification groups in the dropdown, we were able to use the standard [onMarkAsRead](https://github.com/GetStream/react-activity-feed/blob/c3d2d30e41bc44fdfb708ad0a339e304c2b63655/src/Context/FeedManager.js#L589) callback which is passed in as a prop to the `Group` renderable prop to `NotificationDropDown`.

Further more, I also did notice that the callback supports marking all notifications as read if we pass `true` as the argument instead of the current `activity group id`. However, this prop is only populated within `FeedManager` which isn't accessible to `DropdownPanel` -> `Header`.

We've gotten a version to work where we also import `getstream` and making a call directly to stream via the lib.

Example
![sl2lShtj4Z](https://user-images.githubusercontent.com/45951428/60471792-101e9300-9c1b-11e9-98fc-b3551bf5b611.gif)

However the one caveat with that approach is that it doesn't trigger `setState` within the inner notification group components, and we have to close the dropdown and reopen to see the read status updated.

Desired:
![Mhl3TH3PXS](https://user-images.githubusercontent.com/45951428/60471835-2d536180-9c1b-11e9-935d-4c2c51439ebb.gif)

**Comment by JelteF** [comment]
You should be able to use FeedContext.Consumer in your Header component to access this method:
https://github.com/GetStream/react-activity-feed/blob/6e9423f1702094d5883e051c1e7f62d84eee0d8a/src/components/ReactionList.js#L40-L42

**Comment by JelteF** [comment]
Or if you use React 16.6+ you can use the somewhat nicer to use `contextType` API to access the method on `this.context`: https://reactjs.org/docs/context.html#classcontexttype

**Comment by sheng-duetto** [comment]
@JelteF thanks for the suggestion! the `contextType` worked perfectly for our use case.
