### ISSUE TITLE
Any way to automatically load a new activity after posting activity from StatusUpdateForm?

### ISSUE THREAD

**Issue by henryhsue** [GetStream/react-activity-feed#61]
I'd like to request the ability to automatically see your new post after submitting from StatusUpdateForm. Rather than seeing "You have 1 new activity" as a NewActivityNotification, simply refresh the FlatFeed.

**Comment by jaapbakker88** [comment]
@henryhsue this is possible in theory but it will require some complex customisation to our context components. Doing this is very prone to creating bugs. The other option is just refreshing the whole feed when a new activity is posted, but this will create a lot of flickering on the page and the scroll position will get messed up every time something a message is posted. We chose this option as it's default on most websites and.

**Comment by henryhsue** [comment]
I see. No worries, this doesn't seem to be a huge requirement and you're right that other apps and sites have the current option as default. Thanks for the explanation.

**Comment by dubitoergo** [comment]
I'm also looking for some form of flat feed that updates automatically. @jaapbakker88 A notification feed which updates by 'animating in' new activities from the top seems practical (and desirable) for a number of situations. Consider a component functioning as 'history'. If you'd like to update this feed in real-time as a user browses, real-time UI updates would be great. No? Thoughts? What am I missing about react-activity-feed? How would this best be implemented if not that way?

**Comment by onebelarusianguy** [comment]
@dubitoergo Hi, did you find a solution for this? If yes, could you share it?

**Comment by mitroo** [comment]
@jaapbakker88 Is there a way to implement someting close to what @dubitoergo has described?
