### ISSUE TITLE
Multiple Og videos load in StatusUpdateForm but only one shows on the saved activity

### ISSUE THREAD

**Issue by TamaWhiu** [GetStream/react-activity-feed#62]
In the StatusUpdateForm you can attach multiple Og videos from youtube.  They appear on the form with bookmarks and the ability to toggle.  However when saved it only shows one video.

**Steps to Reproduce**

- Navigate to https://getstream.github.io/react-activity-feed/#!/StatusUpdateForm or https://getstream.io/react-activity-feed/tutorial/  and scroll down to Status Updates > "Edit on CodePen"

- In the "New Post" paste in the following links
https://www.youtube.com/watch?v=r1_8rRDHtQ8`
https://www.youtube.com/watch?v=UREUvuS2MsA
   - The video defaults to the first link and a bookmark is displayed below the video
![image](https://user-images.githubusercontent.com/29732486/62366636-09f13e80-b55a-11e9-80a7-4785a2736a58.png)

   - If you click on the 2nd bookmark below the video - the video switches to the 2nd link 
![image](https://user-images.githubusercontent.com/29732486/62366673-24c3b300-b55a-11e9-8aae-a428f9030ed5.png)

- If you save the post, the resulting feed activity only shows the first video.  Ideally it would display both videos and the bookmarks as it does on the StatusUpdateForm
![image](https://user-images.githubusercontent.com/29732486/62366757-58064200-b55a-11e9-9d2a-2e3b92b08cf2.png)

**Comment by jaapbakker88** [comment]
Hi @TamaWhiu! This is how it was designed to work. We chose to use only one Open Graph item per post as it makes sense to have a limit or you would get endless posts.

**Comment by TamaWhiu** [comment]
Thanks for the clarification, initially thought multiple Open Graph items on a single post would work ok.
