### ISSUE TITLE
ActivityFooter component not found

### ISSUE THREAD

**Issue by monirul-hemal** [GetStream/react-activity-feed#64]
There is an ActivityFooter component in the Docs but it's not available to use

**Comment by familywiser1** [comment]
I am also having same issue. ActivityFooter is missing from the package

**Comment by jaapbakker88** [comment]
Hey @monirul-hemal @familywiser1  I added this in version 0.9.24 of react-activity-feed. Can you confirm this fixes this issue for you?

**Comment by tariktuzlakovic** [comment]
Hey @jaapbakker88 I can confirm that 0.9.24 version fixed this issue for me. Thanks!
