### ISSUE TITLE
Update FlatFeed by changing feedGroup property using props?

### ISSUE THREAD

**Issue by familywiser1** [GetStream/react-activity-feed#70]
I want to update flat feed based on the feedGroup property which is updated via props. For ex: 

```
class UserFeed extends React.Component {

    render() {
        const {token, feed_group} = this.props;
        return <StreamApp
                apiKey="123"
                appId="345"
                token={token}
            >
            
                <FlatFeed
                    feedGroup={feed_group}
                    options={{reactions: {recent: true}}}
                    notify
                    Activity={(props) => <CustomActivity {...props}/>}
                />
            </StreamApp>

    }
}
```
StreamApp displays the FlatFeed for the initial value of feedGroup but it does not updateFlatFeed based on different values of feedGroup.

Is there a way to refresh the StreamApp or FlatFeed?

**Comment by jaapbakker88** [comment]
@familywiser1 indeed doing it like this doesn't work, but you can maybe just reload the FlatFeed when you change the prop like this: 
```
class UserFeed extends React.Component {

    render() {
        const {token, feed_group} = this.props;
        return <StreamApp
                apiKey="123"
                appId="345"
                token={token}
            >
            
                {  feed_group === 'xxx' && <FlatFeed
                    feedGroup={feed_group}
                    options={{reactions: {recent: true}}}
                    notify
                    Activity={(props) => <CustomActivity {...props}/>}
                /> }

                {  feed_group === 'xxx' && <FlatFeed
                    feedGroup={feed_group}
                    options={{reactions: {recent: true}}}
                    notify
                    Activity={(props) => <CustomActivity {...props}/>}
                /> }
            </StreamApp>

    }
}
```

**Comment by jaapbakker88** [comment]
Did you figure this problem out?

**Comment by shanemduggan** [comment]
@jaapbakker88 Having some trouble getting the refresh to work. Getting a `this.listRef.onRefresh is not a function` error. Any idea what I'm doing wrong?

**Comment by jaapbakker88** [comment]
@shanemduggan are you still having this issue and if yes, can you provide some more context to this question, maybe share some of your code.

**Comment by manuelurenah** [comment]
@jaapbakker88 I'm having a similar issue regarding to programmatically refresh the `FlatFeed` component. In my case, I'm using the `SinglePost` component to render an Activity in a modal, which supports posting comments to the activity with the `CommentField` component and display the list of comments with the `CommentList` component as well. The issue comes when updating the activity inside the `SinglePost` it doesn't update the `FlatFeed` to take into account the comment count changes.

Your suggestion for using `setListRef={(ref) => this.listRef = ref}` is available for `react-native` but not for `react`. Is there any way to achieve this in react?

**Comment by hmolotsi** [comment]
@manuelurenah Here's an ugly hack that works for me:

`class SocialFeed extends Component {
  containerRef = React.createRef();

  constructor(props) {
    super(props);

    this.state = {
      refreshHack: false,
    };
  }

  componentDidUpdate(prevProps) {
    if (prevProps.feedGroup !== this.props.feedGroup || prevProps.feedId != this.props.feedId) {
      // Hack to force the FlatFeed to update when we change the feedGroup and feedId
      //  because it's not doing this automatically (Stream bug)
      this.setState({ refreshHack: true }, () => {
        setTimeout(() => this.setState({ refreshHack: false }), 200);
      });
    }
  }

  render() {
    return (
      <div style={{ maxWidth: '600px', margin: '0 auto' }} ref={this.containerRef}>
        <StreamApp apiKey={this.apiKey} appId={this.appId} token={this.token}>
          {!this.state.refreshHack && (
            <FlatFeed
              feedGroup={feedGroup}
              userId={feedId}
            />
          )}
        <StreamApp>
      </div>
    );
  }
}`

**Comment by hmolotsi** [comment]
@manuelurenah this worked for me:

```
class SocialFeed extends Component {
  containerRef = React.createRef();

  constructor(props) {
    super(props);

    this.state = {
      refreshHack: false,
    };
  }

  componentDidUpdate(prevProps) {
    if (prevProps.feedGroup !== this.props.feedGroup || prevProps.feedId != this.props.feedId) {
      // Hack to force the FlatFeed to update when we change the feedGroup and feedId
      //  because it's not doing this automatically (Stream bug)
      this.setState({ refreshHack: true }, () => {
        setTimeout(() => this.setState({ refreshHack: false }), 200);
      });
    }
  }

  render() {
    return (
      <div style={{ maxWidth: '600px', margin: '0 auto' }} ref={this.containerRef}>
        <StreamApp apiKey={this.apiKey} appId={this.appId} token={this.token}>
          {!this.state.refreshHack && (
            <FlatFeed
              feedGroup={feedGroup}
              userId={feedId}
            />
          )}
        <StreamApp>
      </div>
    );
  }
}
```
