### ISSUE TITLE
NotificationDropdown is empty after adding new activity into the "notification" feed group in the server-side

### ISSUE THREAD

**Issue by kodah2510** [GetStream/react-activity-feed#73]
Hi, I'm trying to get NotificationDropdown work following this
[https://getstream.io/blog/how-to-build-a-notification-feed-using-stream/](blog), 

Here is the server-side code 
`
let client = stream.connect(API_KEY, SECRET_KEY, APP_ID);
let activity = {
    'actor': 'user' + userId,
    'verb': 'follow',
    'object': 'user' + followId,
};

notificationFeed = client.feed('notification', followId);
notificationFeed.addActivity(activity);
`
Here is the NotificationDropdown setup:

`<NotificationDropdown feedGroup="notification" userId={props.userId} notify={true} right />`

The issue is the notification dropdown is empty after the server return success request.

![image](https://user-images.githubusercontent.com/20522858/69698282-a6a2a200-1130-11ea-838f-5fea1afaf49c.png)

Please help, thank you!

**Comment by Shahzayb** [comment]
Same issue with me. 
here's my backend code:

    
    const shahNotificationFeed = stream.feed('notification', req.user.id.toString());

    const shahFlatFeed = stream.feed('user', req.user.id.toString());
    shahFlatFeed
      .addActivity({
        actor: req.user.id.toString(),
        verb: 'like',
        object: 'book',
        foreign_id: 'like1'
      })
      .then(console.log)
      .catch(console.log);

    const otherFlatFeed = stream.feed('user', 'other');
    otherFlatFeed
      .addActivity({
        actor: 'other',
        verb: 'like',
        object: 'nothing',
        foreign_id: 'like2'
      })
      .then(console.log)
      .catch(console.log);

    shahFlatFeed.follow('user', 'other');

    otherFlatFeed
      .addActivity({
        actor: 'other',
        verb: 'like',
        object: 'still nothing',
        foreign_id: 'like3'
      })
      .then(console.log)
      .catch(console.log);

    shahNotificationFeed.follow('user', 'other');
    shahNotificationFeed.follow('user', req.user.id.toString());

    const userStreamToken = stream.createUserToken(req.user.id.toString());

Here's my front-end code:

    <StreamApp
        apiKey={process.env.REACT_APP_GETSTREAM_API_KEY}
        appId={process.env.REACT_APP_GETSTREAM_APP_ID}
        token={this.props.userStreamToken}
      >
        <NotificationDropdown
          feedGroup="notification"
          userId={this.props.userId}
          notify
        />
      </StreamApp>

-----------------------------
But my I click notification icon, nothing's there:

![image](https://user-images.githubusercontent.com/29760858/69913420-52adfb00-1459-11ea-83bc-8f66d421df19.png)

**Comment by jaapbakker88** [comment]
Hi @kodah2510 can you try the following and see if you get back any results: 

```
<NotificationDropdown 
  feedGroup="notification" 
  userId={props.userId} 
  notify={true} right 
  Group={(group) => console.log(group) || <div>notification</div>}
/>
```

**Comment by yumoraby** [comment]
Having the same issue:

I get the following output in the UI:

![image](https://user-images.githubusercontent.com/44016097/89629536-d1fa9680-d852-11ea-94ec-908801238a10.png)

Console.log
```json
activityGroup:
activities: Array(15)
0:
actor: "System"
foreign_id: ""
id: "be1e5700-d889-11ea-8080-8001657abe83"
object: " profile has been updated"
origin: null
own_reactions: {}
reaction_counts: {}
target: ""
time: "2020-08-07T08:41:10.000000"
verb: "post"
__proto__: Object

```

**Comment by jaapbakker88** [comment]
@yumoraby our default component does not work with all verbs. So as you're actually seeing "notification" being printed out, they are there, they're just not being rendered because we don't support your verb. You would have to supply your own notification component to the Group prop on NotificationDropdown. You can have a look at this component to see how we do this:

https://github.com/GetStream/react-activity-feed/blob/master/src/components/Notification.js

**Comment by yumoraby** [comment]
> @yumoraby our default component does not work with all verbs. So as you're actually seeing "notification" being printed out, they are there, they're just not being rendered because we don't support your verb. You would have to supply your own notification component to the Group prop on NotificationDropdown. You can have a look at this component to see how we do this:
> 
> https://github.com/GetStream/react-activity-feed/blob/master/src/components/Notification.js

Looking at the code i changed the verb to like, repost and still getting the same result.

```json
activityGroup:
activities: Array(1)
0:
actor: "user:SportsLync"
foreign_id: "user:<REDACTED>"
id: "be3e9e00-dc5f-11ea-8080-80001ad5a6f2"
object: "profile has been updated"
origin: null
own_reactions: {}
reaction_counts: {}
target: ""
time: "2020-08-12T05:50:36.000000"
verb: "repost"
__proto__: Object
length: 1
__proto__: Array(0)
activity_count: 1
actor_count: 1
created_at: "2020-08-12T05:50:35.513914"
group: "repost_2020-08-12"
id: "bdf4724b-dc5f-11ea-8080-8000618bef13.repost_2020-08-12"
is_read: false
is_seen: true
updated_at: "2020-08-12T05:50:35.513914"
verb: "repost"
__proto__: Object
feedGroup: "notification"

```

**Comment by jaapbakker88** [comment]
Alright, it's probably going wrong where you're adding the activity, your object is just a string, but it's expecting an object with a verb, actor, etc..
https://github.com/GetStream/react-activity-feed/blob/master/src/components/Notification.js#L119

how are you adding the activity to the notification feed?

**Comment by yumoraby** [comment]
> Alright, it's probably going wrong where you're adding the activity, your object is just a string, but it's expecting an object with a verb, actor, etc..
> https://github.com/GetStream/react-activity-feed/blob/master/src/components/Notification.js#L119
> 
> how are you adding the activity to the notification feed?

the code to create the notification:

``` csharp
        public async static Task CreateNotification(StreamClient client, Guid id, string message)
        {
            string userId = id.ToString();

            try
            {
                var notification = client.Feed("notification", userId);
                Activity activity = new Activity("System", "post", message)
                {
                    Time = DateTime.Now                    
                };
                await notification.AddActivity(activity);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e}");
            }
        }

```

**Comment by jaapbakker88** [comment]
so you're message is a string, this should be an object, with a verb, actor etc.

**Comment by yumoraby** [comment]
Am following the guidance in creating an Activity here. https://github.com/GetStream/stream-net

**Comment by yumoraby** [comment]
Running this code, i can get the page to render:

```javascript
        Group={(props: any) => {
          const items: Types.NotificationGroup = props;
          const activityGroup: Types.ActivityGroup = items.activityGroup;
          const activities: Types.NotificationActivity[] = activityGroup.activities;

          return (
            activities.map((element: Types.NotificationActivity) => <div>{element.object}</div>) || (
              <div>Notification</div>
            )
          );
        }}
```

**Comment by jaapbakker88** [comment]
@yumoraby issue is resolved then?

**Comment by yumoraby** [comment]
> @yumoraby issue is resolved then?

I have a working solution that is handled outside of the formal docs. This may help others who run into this issue as well.

**Comment by jaapbakker88** [comment]
The notification feed is an aggregated feed(eg. x people liked {activity}), now you're extracting the activities out of the group which is possible, but not how it was intended to be used. Glad you resolved your issue, but we won't update this in our docs. I will write a bit on how to write your own notification component.

**Comment by TylerAHolden** [comment]
Can I suggest something being added to the docs to describe this behavior? I couldn't find anything in there explaining this pitfall... The docs just say use a verb so okay I used my own verb unknowing that I would run into this strange issue.

**Comment by pyrytakala** [comment]
+1 for adding this to documentation, e.g. to https://getstream.io/react-activity-feed/tutorial/ and https://getstream.github.io/react-activity-feed/
