### ISSUE TITLE
Missing API to post an activity

### ISSUE THREAD

**Issue by v-yugen** [GetStream/react-activity-feed#75]
Hi,

I would like to understand how to post an activity from our react frontend. The getStream REST documentation seem to have this api but there's no matching API available to use from this react-activity-feed. Could you please help me understand how to do it?
![addActivity](https://user-images.githubusercontent.com/45934458/70208594-019d5000-1754-11ea-9205-fd7f76fa5b33.png)

**Comment by jaapbakker88** [comment]
@v-yugen you want to either use our StatusUpdateForm component or write your own. You can have a look at how it works by looking at: https://github.com/GetStream/react-activity-feed/blob/master/src/components/StatusUpdateForm.js#L316
