### ISSUE TITLE
Missing API documentation for global read and write

### ISSUE THREAD

**Issue by v-yugen** [GetStream/react-activity-feed#76]
Hi,

I've reached to GetStream support and have come to know from them that its feasible to do a global read and write to GetStream if we don't need to tightly couple the feeds from a user. Please read my communication thread with support below.

Could you please guide me to the REST API documentation to understand how to integrate global reads and writes?

----------------------
Thanks for your inquiry.

This is a use case that Stream feeds are well fitted for. They are very customizable. It sounds like if you're using React then you'll need to ask us to make one of your groups global read or read/write. This will decouple the feed from being tied to one user and anyone can read or write to it. Email me at support@getstream with your AppID and the feed group which you'd like to change, along with whether you'd like to be read or read/write when the time comes and I can do this for you.

Best,
Stephen

Hi,

We are developing an application for our customer that helps businesses to effectively plan and track their business changes.

Our application has three core elements, creating initiatives, capture their impacts and defining their actions.

One of the requirement in our product is for the stakeholders of these initiatives to be able to communicate with each other on these initiatives. So be able to like the initiatives, put comments, mention other users, notify each other when an action was taken and so on.

We are evaluating GetStream for this requirement and trying to understand if it best fits into our requirement or not.

We have spent enough time reading the GetStream REST documentation, the core concepts of how feeds and activities are designed. From initial understanding it looks as if the activities are tightly coupled to a user's feed or timeline vs what we need is to be able to add activities against the Initiatives and have multiple users communicate on the same initiative.

Our frontend is built in ReactJs, we have spent about 2-3 days evaluating react-activity-feed package.

We would need help from a support executive from your end to help us to understand if GetStream best fits to our model or not.

Appreciate all the help. Looking forward to a response.

Thank you.

**Comment by tbarbugli** [comment]
Please move this conversation to our official support channels, we only use Github issues for bugs and problems that are related to the projects :)
