### ISSUE TITLE
How do I limit the number of reactions loaded in CommentList?

### ISSUE THREAD

**Issue by rafaelzaleski** [GetStream/react-activity-feed#77]
I'm struggling to figure out how to limit the number of reactions initially loaded by the CommentList component. The default seems to be 5. I have tried to filter the reactions request using the property "doReactionsFilterRequest" but it does not trigger for the first load.

**Comment by jaapbakker88** [comment]
Hi @rafaelzaleski you can pass the recentReactionsLimit in the feed options: 
```
<FlatFeed
  options={{
    recentReactionsLimit={x}
  }}
/>
```

**Comment by rafaelzaleski** [comment]
Thank you, it works!
