### ISSUE TITLE
Override LoadingSpinner in StreamApp component

### ISSUE THREAD

**Issue by CharlieBliss** [GetStream/react-activity-feed#78]
As far as I can tell, there is no way to override the Loading Spinner component in the StreamApp component, so it is difficult to customize the loading state of the stream app. The css is also written inline for the LoadingSpinner component, so it can't be targeted and removed via css directly.

**Comment by jaapbakker88** [comment]
Hi @CharlieBliss  I have just released version `0.9.25` which includes the prop LoadingIndicator on the FlatFeed which allows you to override the LoadingIndicator component.  I also removed the inline styles so you can update them as well.

**Comment by CharlieBliss** [comment]
amazing! thank you!
