### ISSUE TITLE
StreamApp App secret error

### ISSUE THREAD

**Issue by mchong-teal** [GetStream/react-activity-feed#79]
Trying to test out the react components by following the tutorial, but getting the following error:

```
Error: You are publicly sharing your App Secret. Do not expose the App Secret in browsers, "native" mobile apps, or other non-trusted environments.
```

Looks like you can get by that error by passing 'null' as the stream secret to stream.connect, but seems that's being done by the StreamApp component, so not sure if there's a prop I'm missing somewhere?

This is with 0.9.24, just adding the 'StreamApp' component to my app.

**Comment by jaapbakker88** [comment]
@mchong-teal Can you elaborate a bit so I can test this for myself, can you share a link to the tutorial you are following? And please tell me at which step you're stuck with this error.

**Comment by mchong-teal** [comment]
Hey Thanks!

Sorry, just following this tutorial, except I am using an existing app (also built using create-react-app).

https://getstream.io/react-activity-feed/tutorial/
Stuck on the step 'Add Stream to your application', just including the <StreamApp/> component to the app.

Going to try and debug a little bit and can post more details as I go.

Using React v. 16.8.0.

**Comment by jaapbakker88** [comment]
@mchong-teal this error usually occurs if you use the apps secret instead of the token. Of course without looking at your code I can't be certain. But that might be a good starting point to check.

**Comment by mchong-teal** [comment]
Thanks!  The token was the issue; I had mis-copied the token and included some unwanted whitespace.  That being said, the I wonder if the error was a bit misleading..
