### ISSUE TITLE
Unable to use Activity component independently

### ISSUE THREAD

**Issue by v-yugen** [GetStream/react-activity-feed#80]
Hi,

We need to be able to use the activity component independently without needing to use either FlatFeed or SinglePost. 

Below code works find if I use Activity component within FlatFeed or SinglePost but when I render only Activity component then it throws an error (image attached) in console, 

{(this.props.initiativeStream !== null && this.props.initiativeStream !== undefined) ?
          <Activity
            activity={this.props.initiativeStream}
            Footer={
                <CommentField
                  activity={this.props.initiativeStream}
                />
                <CommentList activityId={this.props.initiativeStream.id} />
            }
          />
 :""}

![image](https://user-images.githubusercontent.com/45934458/71438018-fd909c80-2719-11ea-9b3d-d84fbc21e133.png)

**Comment by jaapbakker88** [comment]
Hi @v-yugen, could you wrap your code in a codeblock so I can read it a little bit better? Also, why do you want to use it outside of the FlatFeed or SinglePost?

**Comment by v-yugen** [comment]
Here's the code,
`{(this.props.initiativeStream !== null && this.props.initiativeStream !== undefined) ?
          <Activity
            activity={this.props.initiativeStream}
            Footer={
              <div style={{ padding: '0 16px 16px' }}>
                <CommentField
                  activity={this.props.initiativeStream}
                />
                <CommentList activityId={this.props.initiativeStream.id} />
              </div>
            }
          />
:""}`

**Comment by jaapbakker88** [comment]
So why do you want to use it outside of the FlatFeed or SinglePost components?

**Comment by v-yugen** [comment]
Hi,

I tried to keep the indentation but as soon as I update the comment, the indentation is lost. Sorry!

**Comment by v-yugen** [comment]
We want users of our application to post comments against business entities. 

As per our understanding of GetStream, comments can be posted only against an activity on the feed group. 

If this is true, then we are anticipating to create an activity against each business entity through our application on GetStream. 

Once these activities are created, we need to be able to display and add comments against those entities. See attachment.

If you think we are doing it in wrong way then please suggest alternate approach.

Truely appreciate all the help.
![Requirements](https://user-images.githubusercontent.com/45934458/71581981-ff010100-2b2d-11ea-9438-857b846a6c53.png)

**Comment by jaapbakker88** [comment]
It's true that if you you can only add reactions(such as comments) to activities. But if this is the case I would recommend using the SinglePost component. As this includes a lot of logic related to reactions(comments).

**Comment by v-yugen** [comment]
Yes. thank you. Finally this is how I could integrate it,

As workaround I had to keep Header="" and Content=""

`{(this.props.initiativeStream !== null && this.props.initiativeStream !== undefined) ?
            <SinglePost
              activityId={this.props.initiativeStream.id}
              Activity={(activityProps) => (
                <React.Fragment>
                  <Activity
                    {...activityProps}
                    Header=""
                    Content=""
                    Footer={
                    <div style={{ padding: '0 16px 16px' }}>
                      <CommentField
                        activity={this.props.initiativeStream}
                        onAddReaction={activityProps.onAddReaction}
                      />
                      <CommentList activityId={this.props.initiativeStream.id} />
                    </div>
                    }
                  />
                </React.Fragment>
              )}
            />
          :""}`

After modifying the code to above snippet, we are now unable to post the comment. The CommentField throws below error in console. See attached screenshot,
![PostComment_ConsoleLog](https://user-images.githubusercontent.com/45934458/71582180-05dc4380-2b2f-11ea-8642-22b7e6b5b7c4.png)

This is the token payload that is being used while posting comment. It has been generated on server side,
{
"user_id":"0b2e7322-6042-4669-b0c1-70b4922cd17a"
"resource":"*"
"action":"*"
"feed_id":"*"
}

Could you help me find out what is wrong?

**Comment by v-yugen** [comment]
I have also raised this issue on support ticket,
https://getstream.zendesk.com/hc/en-us/requests/1668

I can see that Stephen has also copied you on this thread.
