### ISSUE TITLE
Don't show alerts please.

### ISSUE THREAD

**Issue by mchong-teal** [GetStream/react-activity-feed#83]
Either the StreamApp or NotificationDropdown component is displaying an alert when a network request fails ('Something went wrong when loading your unread notification counts. Is your internet working?').  I need to be able to disable this and hook into my own error handling behaviour.  Had a moment when my internet was cutting out and got spammed with alerts..

**Comment by jaapbakker88** [comment]
Hi @mchong-teal I'll try to get a fix out for this as soon as possible

**Comment by jaapbakker88** [comment]
@mchong-teal I've release `react-activity-feed@0.9.26` which resolves this issue

**Comment by mchong-teal** [comment]
Great thanks!
