### ISSUE TITLE
App crashes when i delete attachment before upload

### ISSUE THREAD

**Issue by vasanthk97** [GetStream/react-activity-feed#84]
Steps to reproduce : 

Upload attachment.
Cancel it before its uploaded completely

### Error message
**Cannot read property 'id' of undefined**

**Comment by vasanthk97** [comment]
@tbarbugli @vishalnarkhede since we were near to relase and this was a critical issue for us, i have picked up the fix myself and fixed it and raised the PR.  Please look into [this](https://github.com/GetStream/react-activity-feed/pull/86)

**Comment by mahboubii** [comment]
fixed in #164
