### ISSUE TITLE
Emojis loading time is high

### ISSUE THREAD

**Issue by vasanthk97** [GetStream/react-activity-feed#85]
Using the default emoji mart for emoji picker in Status Update Form the time to load emojis is usually 4-5 seconds without caching any js. 

Any fix for this or can someone suggest any optimisation tips?

**Comment by vishalnarkhede** [comment]
Hey @vasanthk97 emoji-mart is quite heavy in fact. We have a plan of of replacing it with some lightweight solution in near future. I will keep you updated about it :)

**Comment by giladkah** [comment]
hey @vishalnarkhede! Any update here?

**Comment by mahboubii** [comment]
[v1](https://github.com/GetStream/react-activity-feed/releases/tag/v1.0.0) ships with a lighter set of emojis and should fix this issue.
