### ISSUE TITLE
Notification feed isssue

### ISSUE THREAD

**Issue by shodgetts** [GetStream/react-activity-feed#87]
Hi get stream team, 

We are currently facing difficulty in integrating getstream notifications in react my react project. 
We are using your react-activity-feed library. 
Use case : 

We want to send some notifications generated by system. Similar to how linkedin sends notifications for new jobs or colleague birthdays. 

Problem : 

We are getting activity group, which is a group of activities as props in the notification Group component.  I simply want it as list of activities. Although i can get list from activity group, the functions, markAsSeen and markAsRead work on activity group. And there is no flag in activity if its seen or read. 

Can you please help me out with this?

Thanks,
Vasanth

**Comment by j86hughes** [comment]
In the case of aggregated feeds where you don't want activities to be aggregated but still keep the mark_read/mark_seen functionality, you can change the aggregation format for that particular feed in your GetStream dashboard like so:

`{{ id }}`

**Comment by ferhatelmas** [comment]
The answer from @j86hughes is correct and complete, closing.
