### ISSUE TITLE
On the example project what do you do after "yarn start"?

### ISSUE THREAD

**Issue by ToddHoff** [GetStream/react-activity-feed#88]
I'm not very familiar with react and there was a lot of issues trying to install this project on macos. 

I see displayed yarn start in the example directory:

rollup v0.68.2
bundles src/index.js → dist/index.js, dist/index.es.js...
created dist/index.js, dist/index.es.js in 3.8s

[2020-02-18 17:30:39] waiting for changes...

No obvious errors. So how do I see  the website?

I started a web server where ever I saw an index.html file and nothing displayed. I tried the react http://localhost:3000/ and "this host could not be reached."

Can someone share the next steps?

thanks

**Comment by vishalnarkhede** [comment]
Hey @ToddHoff 

Please confirm if you did following steps:

```
git clone https://github.com/GetStream/react-activity-feed
cd react-activity-feed
yarn
cd example
yarn
yarn start
```

**Comment by arnautov-anton** [comment]
Closing since there has not been any activity for a while.
